#! /usr/bin/python

import sys, commands, time
import os
os.nice(20)

def main():
  # Everybody! Remember where we parked! -Capt. Kirk
  orig_stdout = sys.stdout

  # Define output file
  f = file('/tmp/11-t-cpu.csv', 'a')
  #Redefine system output to our file
  sys.stdout = f

  # Get the time and date in human-readable form...
  outDate = commands.getoutput("date '+%F %H:%M:%S'")
  # ... and machine-readable form (UNIX-epoch)
  outUxDate =commands.getoutput("date +%s")

  # Read the CPU temperature
  list = commands.getoutput("sensors").splitlines()
  outTemp = list[17].split()[1].decode('ascii','ignore').replace('C','')

  # Read the Motherboard temperature
  outMBTemp = list[16].split()[1].decode('ascii','ignore').replace('C','')

  # Print the data
  print '{0}, {1}, {2}, {3}'.format(outDate, outUxDate, float(outTemp), float(outMBTemp))

  # CLose the file
  f.close()

  # Re-set the stdout
  sys.stdout = orig_stdout

if __name__ == "__main__":
    main()
