#! /usr/bin/python

import sys, commands, time
import os
os.nice(20)

def main():
  # Everybody! Remember where we parked! -Capt. Kirk
  orig_stdout = sys.stdout

  # Define output file
  f = file('/tmp/13-nettraffic.csv', 'a')
  #Redefine system output to our file
  sys.stdout = f

  # Get the time and date in human-readable form...
  outDate = commands.getoutput("date '+%F %H:%M:%S'")
  # ... and machine-readable form (UNIX-epoch)
  outUxDate =commands.getoutput("date +%s")


  # Network traffic
  wlIn = "0"
  wlOut = "0"

  list = commands.getoutput("cat /proc/net/dev").splitlines()
  for line in range(2,len(list)):
    device = list[line].split()[0]
    if device == "lo:":
      loIn = list[line].split()[1]
      loOut = list[line].split()[9]
    if device == "p17p1:":
      p1In = list[line].split()[1]
      p1Out = list[line].split()[9]
    if device == "wlan0:":
      wlIn = list[line].split()[1]
      wlOut = list[line].split()[9]

  # Print the data
  print '{0}, {1}, {2}, {3}, {4}, {5}, {6}, {7}'.format(outDate, outUxDate, loIn, loOut, p1In, p1Out, wlIn, wlOut)

  # CLose the file
  f.close()

  # Re-set the stdout
  sys.stdout = orig_stdout

if __name__ == "__main__":
    main()

