#! /bin/bash

errFile=/tmp/err.err
rmFile=~/bin/run/06-get-load

renice 19 -p $$ >/dev/null
ionice -c 3 -p $$

# Check for the presence of the file to be removed.
if [ -e $rmFile ]; then
    # Remove the file.
    rm $rmFile
    logger -p local7.info -t 00-update-scripts "Script removed ($$)"
fi
