#! /bin/bash

#renice 19 -p $$ >/dev/null
#ionice -c 3 -p $$

mkgrph ()
{
 dbFile=$DATASTORE/$HOST"/12-load-cpu.rrd"
 outDir="/tmp/"$HOST

 # 1. 1min resolution for 24 hours =    1:1440 (1*60*24)              ->1hr graph
 hour=60
 # 2. 5min resolution for 7 days   =    5:2016 (1/5 * 60*24*7)        ->1dy graph
 day=300
 # 3. 1hr resolution for 4 wks     =   60:672  (1/60 * 60*24*7*4)     ->1wk graph
 week=3600
 # 4. 3hr resolution for 4 months  =  180:976  (1/180 * 60*24*30.5*4) ->1mon graph
 month=10800
 # 5. 1dy resolution for 2 yrs     = 1440:732  (1/1440 * 60*24*366*2) ->1yr graph
 year=86400

 if [ -e $dbFile ]; then
  rrdtool graph $outDir".load-cpu-1h.png"       \
  --start 'now - 1h' -e 'now'                   \
  -S $hour                                      \
  -w 200                                        \
  --disable-rrdtool-tag                         \
  --watermark "`date`"                          \
  DEF:l1m=$dbFile:load01:AVERAGE                 \
  LINE1:l1m#FF0000:"(1')"

  rrdtool graph $outDir".load-cpu-1d.png"       \
  --start 'now - 24h' -e 'now'                  \
  -S $day                                       \
  --disable-rrdtool-tag                         \
  --units-exponent 0                            \
  --watermark "`date`"                          \
  DEF:l1m=$dbFile:load01:AVERAGE                \
  DEF:l1min=$dbFile:load01:MIN                  \
  DEF:l1max=$dbFile:load01:MAX                  \
  CDEF:l1rng=l1max,l1min,-                      \
  LINE1:l1min                                   \
  AREA:l1rng#BABAF7::STACK                      \
  LINE1:l1m#FF0000:"(1')"

  rrdtool graph $outDir".load-cpu-1w.png"       \
  --start 'now - 1w' -e 'now'                   \
  -S $week                                      \
  --disable-rrdtool-tag                         \
  --alt-autoscale-max                           \
  --units-exponent 0                            \
  --watermark "`date`"                          \
  DEF:l1m=$dbFile:load01:AVERAGE                \
  DEF:l1min=$dbFile:load01:MIN                  \
  DEF:l1max=$dbFile:load01:MAX                  \
  CDEF:l1rng=l1max,l1min,-                      \
  LINE1:l1min                                   \
  AREA:l1rng#BABAF7::STACK                      \
  LINE1:l1m#FF0000:"(1')"

  rrdtool graph $outDir".load-cpu-1m.png"       \
  --start 'now - 1 month' -e 'now'              \
  -S $month                                     \
  --disable-rrdtool-tag                         \
  --alt-autoscale-max                           \
  --units-exponent 0                            \
  --watermark "`date`"                          \
  DEF:l1m=$dbFile:load01:AVERAGE                \
  DEF:l1min=$dbFile:load01:MIN                  \
  DEF:l1max=$dbFile:load01:MAX                  \
  CDEF:l1rng=l1max,l1min,-                      \
  LINE1:l1min                                   \
  AREA:l1rng#BABAF7::STACK                      \
  LINE1:l1m#FF0000:"(1')"

  rrdtool graph $outDir".load-cpu-1y.png"       \
  --start 'now - 1 year' -e 'now'               \
  -S $year                                      \
  --disable-rrdtool-tag                         \
  --alt-autoscale-max                           \
  --units-exponent 0                            \
  --watermark "`date`"                          \
  DEF:l1m=$dbFile:load01:AVERAGE                \
  DEF:l1min=$dbFile:load01:MIN                  \
  DEF:l1max=$dbFile:load01:MAX                  \
  CDEF:l1rng=l1max,l1min,-                      \
  LINE1:l1min                                   \
  AREA:l1rng#BABAF7::STACK                      \
  LINE1:l1m#FF0000:"(1')"

  rrdtool graph $outDir".processes-1w.png"       \
  --start 'now - 1w' -e 'now'                   \
  -S $week                                      \
  --disable-rrdtool-tag                         \
  --units-exponent 0                            \
  --watermark "`date`"                          \
  DEF:cnt=$dbFile:lastpid:AVERAGE                \
  DEF:cntmin=$dbFile:lastpid:MIN                  \
  DEF:cntmax=$dbFile:lastpid:MAX                  \
  CDEF:cntrng=cntmax,cntmin,-                      \
  LINE1:cntmin                                   \
  AREA:cntrng#BABAF7::STACK                      \
  LINE1:cnt#FF0000:"(processes per second)"

#  convert $outDir".load-cpu-1h.png" -chop '20x0+2+0' $outDir".load-cpu-1h.png"
#  convert $outDir".load-cpu-1d.png" -chop '20x0+2+0' $outDir".load-cpu-1d.png"
#  convert $outDir".load-cpu-1w.png" -chop '20x0+2+0' $outDir".load-cpu-1w.png"
#  convert $outDir".load-cpu-1m.png" -chop '20x0+2+0' $outDir".load-cpu-1m.png"
#  convert $outDir".load-cpu-1y.png" -chop '20x0+2+0' $outDir".load-cpu-1y.png"

 fi
}

DATASTORE="/srv/array1/datastore"
HOST="boson"
mkgrph >/dev/null

HOST="rbian"
#mkgrph >/dev/null

HOST="rbups"
#mkgrph >/dev/null

HOST="rbelec"
#mkgrph >/dev/null

HOST="rxbmc"
#mkgrph >/dev/null

HOST="neutron"
#mkgrph >/dev/null

HOST="bbone"
#mkgrph >/dev/null
