#! /bin/bash

#renice 19 -p $$ >/dev/null
#ionice -c 3 -p $$

mkgrph ()
{
 dbFile=$DATASTORE/$HOST"/12-load-cpu.rrd"
 outDir="/tmp/"$HOST

 # 1. 1min resolution for 24 hours =    1:1440 (1*60*24)              ->1hr graph
 hour=60
 # 2. 5min resolution for 7 days   =    5:2016 (1/5 * 60*24*7)        ->1dy graph
 day=300
 # 3. 1hr resolution for 4 wks     =   60:672  (1/60 * 60*24*7*4)     ->1wk graph
 week=3600
 # 4. 3hr resolution for 4 months  =  180:976  (1/180 * 60*24*30.5*4) ->1mon graph
 month=10800
 # 5. 1dy resolution for 2 yrs     = 1440:732  (1/1440 * 60*24*366*2) ->1yr graph
 year=86400
# user, idle, wait, system
def1=" DEF:us=$dbFile:user:AVERAGE DEF:id=$dbFile:idle:AVERAGE DEF:wa=$dbFile:wait:AVERAGE DEF:sy=$dbFile:system:AVERAGE  DEF:ld=$dbFile:load01:AVERAGE"
 if [ -e $dbFile ]; then
  rrdtool graph $outDir".load-cpu-1h.png"       \
  --start 'now - 1h' -e 'now'                   \
  -S $hour                                      \
  -w 200                                        \
  --disable-rrdtool-tag                         \
  --watermark "`date`"                          \
  --upper-limit 100                             \
  --lower-limit 0                               \
  --rigid                                       \
  --right-axis 0.02:0                           \
  --right-axis-format "%.1lf"                   \
  $def1                                         \
  CDEF:scaled_ld=ld,50,*                        \
  AREA:us#FF0000:                       \
  AREA:sy#FFFF00::STACK                   \
  AREA:wa#0000FF::STACK                   \
  AREA:id#00AA00::STACK                   \
  LINE0.5:scaled_ld#000000:"Load"

  convert $outDir".load-cpu-1h.png" -gravity East -chop '36x0+2+0' $outDir".load-cpu-1h.png"

  rrdtool graph $outDir".load-cpu-1d.png"       \
  --start 'now - 24h' -e 'now'                  \
  -S $day                                       \
  --disable-rrdtool-tag                         \
  --watermark "`date`"                          \
  --upper-limit 100                              \
  --lower-limit 0                               \
  --rigid                                       \
  $def1                                         \
  CDEF:scaled_ld=ld,50,*                        \
  AREA:us#FF0000:"User"                       \
  AREA:sy#FFFF00:"System":STACK                   \
  AREA:wa#0000FF:"Wait":STACK                   \
  AREA:id#00AA00:"Idle":STACK                   \
  LINE0.5:scaled_ld#000000:"Load"

  rrdtool graph $outDir".load-cpu-1w.png"       \
  --start 'now - 1w' -e 'now'                   \
  -S $week                                      \
  --disable-rrdtool-tag                         \
  --watermark "`date`"                          \
  --upper-limit 100                              \
  --lower-limit 0                               \
  --rigid                                       \
  $def1                                         \
  CDEF:scaled_ld=ld,50,*                        \
  AREA:us#FF0000:"User"                       \
  AREA:sy#FFFF00:"System":STACK                   \
  AREA:wa#0000FF:"Wait":STACK                   \
  AREA:id#00AA00:"Idle":STACK                   \
  LINE0.5:scaled_ld#000000:"Load"

  rrdtool graph $outDir".load-cpu-1m.png"       \
  --start 'now - 1 month' -e 'now'              \
  -S $month                                     \
  --disable-rrdtool-tag                         \
  --watermark "`date`"                          \
  --upper-limit 100                              \
  --lower-limit 0                               \
  --rigid                                       \
  --right-axis 0.02:0                            \
  --right-axis-format "%.1lf"                   \
  $def1                                         \
  CDEF:scaled_ld=ld,50,*                        \
  AREA:us#FF0000:"User"                       \
  AREA:sy#FFFF00:"System":STACK                   \
  AREA:wa#0000FF:"Wait":STACK                   \
  AREA:id#00AA00:"Idle":STACK                   \
  LINE0.5:scaled_ld#000000:"Load"

  rrdtool graph $outDir".load-cpu-1y.png"       \
  --start 'now - 1 year' -e 'now'               \
  -S $year                                      \
  --disable-rrdtool-tag                         \
  --watermark "`date`"                          \
  --upper-limit 100                              \
  --lower-limit 0                               \
  --rigid                                       \
  $def1                                         \
  CDEF:scaled_ld=ld,50,*                        \
  AREA:us#FF0000:"User"                       \
  AREA:sy#FFFF00:"System":STACK                   \
  AREA:wa#0000FF:"Wait":STACK                   \
  AREA:id#00AA00:"Idle":STACK                   \
  LINE0.5:scaled_ld#000000:"Load"
 fi
}

DATASTORE="/srv/array1/datastore"
HOST="boson"
mkgrph >/dev/null

HOST="rbian"
#mkgrph >/dev/null

HOST="rbups"
#mkgrph >/dev/null

HOST="rbelec"
#mkgrph >/dev/null

HOST="rxbmc"
#mkgrph >/dev/null

HOST="neutron"
#mkgrph >/dev/null

HOST="bbone"
#mkgrph >/dev/null
