#! /bin/bash

#renice 19 -p $$ >/dev/null
#ionice -c 3 -p $$

mkgrph ()
{
 dbFile=$DATASTORE/$HOST"/15-cnt-loglines.rrd"
 outDir="/tmp/"$HOST
# outDir="/srv/array1/public/"$HOST

 # temperature samples consolidations provided
# ds1="DS:t_cpu:GAUGE:360:U:U"
# ds2="DS:t_sys:GAUGE:360:U:U"
 # 1. 1min resolution for 24 hours =    1:1440 (1*60*24)              ->1hr graph
 hour=60
 # 2. 5min resolution for 7 days   =    5:2016 (1/5 * 60*24*7)        ->1dy graph
 day=300
 # 3. 1hr resolution for 4 wks     =   60:672  (1/60 * 60*24*7*4)     ->1wk graph
 week=3600
 # 4. 3hr resolution for 4 months  =  180:976  (1/180 * 60*24*30.5*4) ->1mon graph
 month=10800
 # 5. 1dy resolution for 2 yrs     = 1440:732  (1/1440 * 60*24*366*2) ->1yr graph
 year=86400

 if [ -e $dbFile ]; then
  rrdtool graph $outDir".c-log-1h.png"          \
  --start 'now - 1h' -e 'now'                   \
  -S $hour                                      \
  -w 200                                        \
  --disable-rrdtool-tag                         \
  --watermark "`date`"                          \
  DEF:akrn=$dbFile:krnlog:AVERAGE                 \
  DEF:asys=$dbFile:syslog:AVERAGE                 \
  DEF:ames=$dbFile:meslog:AVERAGE                 \
  CDEF:krn=akrn,$hour,* \
  CDEF:sys=asys,$hour,* \
  CDEF:mes=ames,$hour,* \
  AREA:sys#BAF7BA:"total"                       \
  AREA:mes#0000FF:"warning"   \
  AREA:krn#FF0000:">= error"

  rrdtool graph $outDir".c-log-1d.png"          \
  --start 'now - 24h' -e 'now'                  \
  -S $day                                       \
  --disable-rrdtool-tag                         \
  --watermark "`date`"                          \
  DEF:akrn=$dbFile:krnlog:AVERAGE                 \
  DEF:asys=$dbFile:syslog:AVERAGE                 \
  DEF:ames=$dbFile:meslog:AVERAGE                 \
  CDEF:krn=akrn,$day,*,5,/ \
  CDEF:sys=asys,$day,*,5,/ \
  CDEF:mes=ames,$day,*,5,/ \
  AREA:sys#BAF7BA:"total"                       \
  AREA:mes#0000FF:"warning"   \
  AREA:krn#FF0000:">= error"

  rrdtool graph $outDir".c-log-1w.png"          \
  --start 'now - 1w' -e 'now'                   \
  -S $week                                      \
  --disable-rrdtool-tag                         \
  --watermark "`date`"                          \
  --vertical-label "[lines/min]"                     \
  DEF:akrn=$dbFile:krnlog:AVERAGE                 \
  DEF:asys=$dbFile:syslog:AVERAGE                 \
  DEF:ames=$dbFile:meslog:AVERAGE                 \
  CDEF:krn=akrn,$week,*,60,/ \
  CDEF:sys=asys,$week,*,60,/ \
  CDEF:mes=ames,$week,*,60,/ \
  AREA:sys#BAF7BA:"total"                       \
  AREA:mes#0000FF:"warning"   \
  AREA:krn#FF0000:">= error"

  rrdtool graph $outDir".c-log-1m.png"          \
  --start 'now - 1 month' -e 'now'              \
  -S $month                                     \
  --disable-rrdtool-tag                         \
  --watermark "`date`"                          \
  DEF:akrn=$dbFile:krnlog:AVERAGE                 \
  DEF:asys=$dbFile:syslog:AVERAGE                 \
  DEF:ames=$dbFile:meslog:AVERAGE                 \
  CDEF:krn=akrn,$month,*,180,/ \
  CDEF:sys=asys,$month,*,180,/ \
  CDEF:mes=ames,$month,*,180,/ \
  AREA:sys#BAF7BA:"total"                       \
  AREA:mes#0000FF:"warning"   \
  AREA:krn#FF0000:">= error"

  rrdtool graph $outDir".c-log-1y.png"          \
  --start 'now - 1 year' -e 'now'               \
  -S $year                                      \
  --disable-rrdtool-tag                         \
  --watermark "`date`"                          \
  --vertical-label "[lines/min]"                     \
  DEF:akrn=$dbFile:krnlog:AVERAGE                 \
  DEF:asys=$dbFile:syslog:AVERAGE                 \
  DEF:ames=$dbFile:meslog:AVERAGE                 \
  CDEF:krn=akrn,$year,*,1440,/ \
  CDEF:sys=asys,$year,*,1440,/ \
  CDEF:mes=ames,$year,*,1440,/ \
  AREA:sys#BAF7BA:"total"                       \
  AREA:mes#0000FF:"warning"   \
  AREA:krn#FF0000:">= error"

 fi
}

DATASTORE="/srv/array1/datastore"
HOST="rbian"
#mkgrph >/dev/null

HOST="boson"
mkgrph >/dev/null

HOST="neutron"
#mkgrph >/dev/null

HOST="rbelec"
#mkgrph >/dev/null

HOST="rbups"
#mkgrph >/dev/null

HOST="rxbmc"
#mkgrph >/dev/null

HOST="bbone"
#mkgrph >/dev/null

