#! /bin/bash

#renice 19 -p $$ >/dev/null
#ionice -c 3 -p $$

mkgrph ()
{
 dbFile=$DATASTORE/$HOST"/19-tempdisk.rrd"
 outDir="/tmp/"$HOST

 # temperature samples consolidations provided
def1="  DEF:d0=$dbFile:disk0:AVERAGE DEF:d1=$dbFile:disk1:AVERAGE DEF:d2=$dbFile:disk2:AVERAGE DEF:d3=$dbFile:disk3:AVERAGE DEF:d4=$dbFile:disk4:AVERAGE  "

 # 1. 1min resolution for 24 hours =    1:1440 (1*60*24)              ->1hr graph
 hour=60
 # 2. 5min resolution for 7 days   =    5:2016 (1/5 * 60*24*7)        ->1dy graph
 day=300
 # 3. 1hr resolution for 4 wks     =   60:672  (1/60 * 60*24*7*4)     ->1wk graph
 week=3600
 # 4. 3hr resolution for 4 months  =  180:976  (1/180 * 60*24*30.5*4) ->1mon graph
 month=10800
 # 5. 1dy resolution for 2 yrs     = 1440:732  (1/1440 * 60*24*366*2) ->1yr graph
 year=86400

 if [ -e $dbFile ]; then
  rrdtool graph $outDir".t-disk-1h.png"          \
  --start 'now - 1h' -e 'now'                   \
  -S $hour                                      \
  -w 200                                        \
  --alt-autoscale             \
  --disable-rrdtool-tag                         \
  --watermark "`date`"                          \
  $def1 \
  LINE2:d0#111111:"SSD"                     \
  LINE1:d1#FF0000:".1"                     \
  LINE1:d2#006600:".2"                     \
  LINE1:d3#BB00BB:".3"                     \
  LINE1:d4#0000FF:".4"

  rrdtool graph $outDir".t-disk-1d.png"          \
  --start 'now - 24h' -e 'now'                   \
  -S $day                                      \
  --disable-rrdtool-tag                         \
  --alt-autoscale             \
  --watermark "`date`"                          \
  $def1 \
  LINE2:d0#111111:"SSD"                     \
  LINE1:d1#FF0000:"disk.1"                     \
  LINE1:d2#006600:".2"                     \
  LINE1:d3#BB00BB:".3"                     \
  LINE1:d4#0000FF:".4"

  rrdtool graph $outDir".t-disk-1w.png"          \
  --start 'now - 1 week' -e 'now'                   \
  -S $week                                      \
  --disable-rrdtool-tag                         \
  --alt-autoscale             \
  --watermark "`date`"                          \
  $def1 \
  LINE2:d0#111111:"SSD"                     \
  LINE1:d1#FF0000:"disk.1"                     \
  LINE1:d2#006600:".2"                     \
  LINE1:d3#BB00BB:".3"                     \
  LINE1:d4#0000FF:".4"

  rrdtool graph $outDir".t-disk-1m.png"          \
  --start 'now - 1 month' -e 'now'                   \
  -S $month                                      \
  --disable-rrdtool-tag                         \
  --alt-autoscale             \
  --watermark "`date`"                          \
  $def1 \
  LINE2:d0#111111:"SSD"                     \
  LINE1:d1#FF0000:"disk.1"                     \
  LINE1:d2#006600:".2"                     \
  LINE1:d3#BB00BB:".3"                     \
  LINE1:d4#0000FF:".4"

  rrdtool graph $outDir".t-disk-1y.png"          \
  --start 'now - 1 year' -e 'now'                   \
  -S $year                                      \
  --disable-rrdtool-tag                         \
  --alt-autoscale             \
  --watermark "`date`"                          \
  $def1 \
  LINE2:d0#111111:"SSD"                     \
  LINE1:d1#FF0000:"disk.1"                     \
  LINE1:d2#006600:".2"                     \
  LINE1:d3#BB00BB:".3"                     \
  LINE1:d4#0000FF:".4"

 fi
}

DATASTORE="/srv/array1/datastore"
HOST="boson"
mkgrph >/dev/null

