#! /bin/bash

#renice 19 -p $$ >/dev/null
#ionice -c 3 -p $$

mkgrph ()
{
 dbFile=$DATASTORE/$HOST"/16-aux-ups.rrd"
 outDir="/tmp/aux"

 # 1. 1min resolution for 24 hours =    1:1440 (1*60*24)              ->1hr graph
 hour=60
 # 2. 5min resolution for 7 days   =    5:2016 (1/5 * 60*24*7)        ->1dy graph
 day=300
 # 3. 1hr resolution for 4 wks     =   60:672  (1/60 * 60*24*7*4)     ->1wk graph
 week=3600
 # 4. 3hr resolution for 4 months  =  180:976  (1/180 * 60*24*30.5*4) ->1mon graph
 month=10800
 # 5. 1dy resolution for 2 yrs     = 1440:732  (1/1440 * 60*24*366*2) ->1yr graph
 year=86400

 if [ -e $dbFile ]; then
  rrdtool graph $outDir"."$ds1"-1h.png"          \
  --start 'now - 1h' -e 'now'                   \
  -S $hour                                      \
  -w 200                                        \
  --disable-rrdtool-tag                         \
  --alt-autoscale                      \
  --alt-y-grid                         \
  --watermark "`date`"                          \
  DEF:prm=$dbFile:$ds1:AVERAGE                 \
  LINE1:prm#FF0000

  rrdtool graph $outDir"."$ds1"-1d.png"          \
  --start 'now - 24h' -e 'now'                  \
  -S $day                                       \
  --disable-rrdtool-tag                         \
  --alt-autoscale                      \
  --alt-y-grid                         \
  --watermark "`date`"                          \
  DEF:prm=$dbFile:$ds1:AVERAGE                \
  DEF:prmin=$dbFile:$ds1:MIN                   \
  DEF:prmax=$dbFile:$ds1:MAX                   \
  CDEF:prng=prmax,prmin,-                      \
  LINE1:prmin                                   \
  AREA:prng#BABAF7::STACK                      \
  LINE1:prm#FF0000

  rrdtool graph $outDir"."$ds1"-1w.png"          \
  --start 'now - 1w' -e 'now'                   \
  -S $week                                      \
  --disable-rrdtool-tag                         \
  --alt-autoscale                      \
  --alt-y-grid                         \
  --watermark "`date`"                          \
  DEF:prm=$dbFile:$ds1:AVERAGE                \
  DEF:prmin=$dbFile:$ds1:MIN                   \
  DEF:prmax=$dbFile:$ds1:MAX                   \
  CDEF:prng=prmax,prmin,-                      \
  LINE1:prmin                                   \
  AREA:prng#BABAF7::STACK                      \
  LINE1:prm#FF0000

  rrdtool graph $outDir"."$ds1"-1m.png"          \
  --start 'now - 1 month' -e 'now'              \
  -S $month                                     \
  --disable-rrdtool-tag                         \
  --alt-autoscale                      \
  --alt-y-grid                         \
  --watermark "`date`"                          \
  DEF:prm=$dbFile:$ds1:AVERAGE                \
  DEF:prmin=$dbFile:$ds1:MIN                   \
  DEF:prmax=$dbFile:$ds1:MAX                   \
  CDEF:prng=prmax,prmin,-                      \
  LINE1:prmin                                   \
  AREA:prng#BABAF7::STACK                      \
  LINE1:prm#FF0000

  rrdtool graph $outDir"."$ds1"-1y.png"            \
  --start 'now - 1 year' -e 'now'               \
  -S $year                                      \
  --disable-rrdtool-tag                         \
  --alt-autoscale                      \
  --alt-y-grid                         \
  --watermark "`date`"                          \
  DEF:prm=$dbFile:$ds1:AVERAGE                \
  DEF:prmin=$dbFile:$ds1:MIN                   \
  DEF:prmax=$dbFile:$ds1:MAX                   \
  CDEF:prng=prmax,prmin,-                      \
  LINE1:prmin                                   \
  AREA:prng#BABAF7::STACK                      \
  LINE1:prm#FF0000

 fi
}

DATASTORE="/srv/array1/datastore"

ds1=Vin
HOST="rbups"
#mkgrph >/dev/null

ds1=Vbat
#mkgrph >/dev/null

ds1=CHRGbat
#mkgrph >/dev/null

ds1=UPSload
#mkgrph >/dev/null

ds1=RUNbat
#mkgrph >/dev/null
